basic_cleaning:
  input_artifact: sample2.csv:latest
  max_price: 350
  min_price: 10
  output_artifact: clean_data.csv
  output_description: Cleaned dataset from sample.csv
  output_type: clean_data
data_check:
  kl_threshold: 0.2
data_split:
  input_artifact: clean_data.csv:latest
  output_description: Train+Val and Test splits
  output_type: processed_data
  random_seed: 42
  stratify_by: neighbourhood_group
  test_artifact: test_data.csv
  test_size: 0.2
  trainval_artifact: trainval_data.csv
  val_size: 0.2
etl:
  max_price: 350
  min_price: 10
  sample: sample1.csv
main:
  components_repository: https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#components
  experiment_name: development
  project_name: nyc_airbnb
  steps: all
modeling:
  max_tfidf_features: 5
  output_artifact: random_forest_export
  random_forest:
    criterion: squared_error
    max_depth: 50
    min_samples_leaf: 3
    min_samples_split: 4
    n_estimators: 200
    n_jobs: -1
    oob_score: true
  random_seed: 42
  stratify_by: neighbourhood_group
  test_size: 0.2
  val_size: 0.2
